[package]
name = "WebCrane"
version = "0.1.0"
edition = "2021"

[dependencies]
easy-upnp = "0.2.1"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
tokio-tungstenite = "0.26.1"
futures-util = "0.3.31"
ignore = "0.4.23"
sha2 = "0.10.8"
serde_json = "1.0.140"
bincode = { version = "2.0.1", features = ["serde"] }
toml = "0.8.20"
base64 = "0.22.1"
indicatif = "0.17.11"
